version: '3'

services:
  server:
    build: server/
    volumes:
      - raft-kv:/usr/app/raft-kv
    ports:
      - 5440:5440

  client:
    build: client/
    # client container can access the localhost of the computer.
    # network_mode: host
    ports:
      - 9000:9000
    # should wait until server is ready before launching.
    depends_on:
      - server

volumes:
  raft-kv:
    name: raft-kv