# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import numstore_pb2 as numstore__pb2


class NumStoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetNum = channel.unary_unary(
                '/NumStore/SetNum',
                request_serializer=numstore__pb2.SetNumRequest.SerializeToString,
                response_deserializer=numstore__pb2.SetNumResponse.FromString,
                )
        self.Fact = channel.unary_unary(
                '/NumStore/Fact',
                request_serializer=numstore__pb2.FactRequest.SerializeToString,
                response_deserializer=numstore__pb2.FactResponse.FromString,
                )


class NumStoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetNum(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Fact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NumStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetNum': grpc.unary_unary_rpc_method_handler(
                    servicer.SetNum,
                    request_deserializer=numstore__pb2.SetNumRequest.FromString,
                    response_serializer=numstore__pb2.SetNumResponse.SerializeToString,
            ),
            'Fact': grpc.unary_unary_rpc_method_handler(
                    servicer.Fact,
                    request_deserializer=numstore__pb2.FactRequest.FromString,
                    response_serializer=numstore__pb2.FactResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'NumStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NumStore(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetNum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/NumStore/SetNum',
            numstore__pb2.SetNumRequest.SerializeToString,
            numstore__pb2.SetNumResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Fact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/NumStore/Fact',
            numstore__pb2.FactRequest.SerializeToString,
            numstore__pb2.FactResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
