services:
    server-1:
        image: kvstore
        volumes:
            - "../server/server.sh:/start.sh"
            - "../logs/logcache/server1:/raft-kv-store/logs/logcache"
        ports:
            - "127.0.0.1:5440:5440"
            - "127.0.0.1:4000:4000"
        environment:
            - NAME=server-1
            - IS_LEADER=FALSE
            - IS_UNRESPONSIVE=FALSE
            - PEER_IPS=server-2:4000,server-3:4000
            # - MEMCACHED_HOST=memcached

    server-2:
        image: kvstore
        volumes:
            - "../server/server.sh:/start.sh"
            - "../logs/logcache/server2:/raft-kv-store/logs/logcache"
        ports:
            - "127.0.0.1:5441:5440"
            - "127.0.0.1:4001:4000"
        environment:
            - NAME=server-2
            - IS_LEADER=FALSE
            - IS_UNRESPONSIVE=FALSE
            - PEER_IPS=server-1:4000,server-3:4000
            # - MEMCACHED_HOST=memcached

    server-3:
        image: kvstore
        volumes:
            - "../server/server.sh:/start.sh"
            - "../logs/logcache/server3:/raft-kv-store/logs/logcache"
        ports:
            - "127.0.0.1:5442:5440"
            - "127.0.0.1:4002:4000"
        environment:
            - NAME=server-3
            - IS_LEADER=FALSE
            - IS_UNRESPONSIVE=FALSE
            - PEER_IPS=server-1:4000,server-2:4000
            # - MEMCACHED_HOST=memcached
    
    # server-4:
    #     image: kvstore
    #     volumes:
    #         - "../server/server.sh:/start.sh"
    #         - "../logs/logcache/server4:/raft-kv-store/logs/logcache"
    #     ports:
    #         - "127.0.0.1:5443:5440"
    #         - "127.0.0.1:4003:4000"
    #     environment:
    #         - NAME=server-4
    #         - IS_LEADER=FALSE
    #         - IS_UNRESPONSIVE=FALSE
    #         - PEER_IPS=server-1:4000,server-2:4000,server-3:4000,server-5:4000
    #         # - MEMCACHED_HOST=memcached

    # memcached:
    #     image: memcached:alpine

    # server-4:
    #     image: kvstore
    #     volumes:
    #         - "../server/server.sh:/start.sh"
    #         - "../logs/logcache/server4:/raft-kv-store/logs/logcache"
    #     ports:
    #         - "127.0.0.1:5443:5440"
    #         - "127.0.0.1:4003:4000"
    #     environment:
    #         - NAME=server-4
    #         - IS_LEADER=FALSE
    #         - IS_UNRESPONSIVE=FALSE
    #         - PEER_IPS=server-1:4000,server-2:4000,server-3:4000


#    client:
#        image: kvstore
#        volumes:
#            - "../client/client.sh:/start.sh"
#            - "../server/logs/logcache:/raft-kv-store/logs/logcache"
#        # client container can access the localhost of the computer.
#        # network_mode: host
#        # should wait until all the servers are ready.
#        depends_on:
#            - server-1
#            - server-2
#            - server-3
    # server-5:
    #     image: kvstore
    #     volumes:
    #         - "../server/server.sh:/start.sh"
    #         - "../logs/logcache/server5:/raft-kv-store/logs/logcache"
    #     ports:
    #         - "127.0.0.1:5444:5440"
    #         - "127.0.0.1:4004:4000"
    #     environment:
    #         - NAME=server-5
    #         - IS_LEADER=FALSE
    #         - IS_UNRESPONSIVE=FALSE
    #         - PEER_IPS=server-1:4000,server-2:4000,server-3:4000,server-4:4000
    #         # - MEMCACHED_HOST=memcached
